name: Stock Analysis Workflow

on:
  schedule:
    # 日本時間 AM 06:05 (UTC 21:05) に、両方のジョブをほぼ同時に開始
    - cron: '5 21 * * 1-5'
  workflow_dispatch:

jobs:
  # === Job 1: 今日の通知と、次回のシミュレーションのためのデータ保存 ===
  notify_job:
    name: Step A - Fetch and Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-python@v5
        with: { python-version: '3.11' }
      - name: Install and Run
        run: |
          pip install -r requirements.txt
          python step_a_notify.py
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
      - uses: actions/upload-artifact@v4
        with:
          name: watchlist-artifacts # 監視リストだけを保存
          path: output/watchlist_*.csv

  # === Job 2: 前営業日の答え合わせ（シミュレーション） ===
  simulate_job:
    name: Step B - Simulate Previous Day
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: output # 過去の全てのArtifactsをダウンロード
      - name: Install and Run
        run: |
          pip install -r requirements.txt
          python step_b_simulate.py
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: result-artifacts # 結果だけを保存
          path: output/results.csv
