name: Stock Analysis Workflow

on:
  schedule:
    - cron: '5 20 * * 1-5'
  workflow_dispatch:

jobs:
  # === Job 1: 仕事A (データを取得し、通知まで行う) ===
  fetch_and_notify:
    name: Step A - Fetch and Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install and Run
        run: |
          pip install -r requirements.txt
          # ★★★ 正しいファイル名: task_a_notify.py ★★★
          python task_a_notify.py
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
      - uses: actions/upload-artifact@v4
        with:
          # ★★★ 常に同じ名前で、フォルダごと保存 ★★★
          name: analysis-artifacts
          path: output/

  # === Job 2: 仕事B (シミュレーション専門) ===
  simulate:
    name: Step B - Simulate
    runs-on: ubuntu-latest
    needs: fetch_and_notify # Job Aの成功を待つ
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          # ★★★ 常に同じ名前で、フォルダごとダウンロード ★★★
          name: analysis-artifacts
          path: output
      - name: Install and Run
        run: |
          pip install -r requirements.txt
          # ★★★ 正しいファイル名: task_b_simulate.py ★★★
          python task_b_simulate.py
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          # ★★★ 常に同じ名前で、フォルダごと上書き保存 ★★★
          name: analysis-artifacts
          path: output/
