name: Stock Analysis Workflow

on:
  schedule:
    - cron: '5 20 * * 1-5'
  workflow_dispatch:

jobs:
  run_all:
    name: Run Full Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install and Run Scripts
        run: |
          pip install -r requirements.txt
          python step_a_fetch.py
          python step_b_notify.py
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
      - uses: actions/upload-artifact@v4
        with:
          name: analysis-artifacts
          path: output/
