name: Stock Analysis Workflow

on:
  schedule:
    - cron: '5 20 * * 1-5'
  workflow_dispatch:

jobs:
  fetch_and_notify:
    name: Step A - Fetch and Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install and Run
        run: |
          pip install -r requirements.txt
          python job_a.py
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
      - uses: actions/upload-artifact@v4
        with:
          # ★★★ watchlistだけを保存 ★★★
          name: watchlist-artifact
          path: output/watchlist_*.csv

  simulate:
    name: Step B - Simulate
    runs-on: ubuntu-latest
    needs: fetch_and_notify
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      
      # ★★★ watchlistと、過去のresultsの両方をダウンロード ★★★
      - name: Download Watchlist
        uses: actions/download-artifact@v4
        with:
          name: watchlist-artifact
          path: output
      - name: Download Previous Results (if exists)
        uses: actions/download-artifact@v4
        with:
          name: results-artifact
          path: output
        continue-on-error: true # resultsがまだなくてもエラーにしない

      - name: Install and Run
        run: |
          pip install -r requirements.txt
          python job_b.py
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
          
      # ★★★ results.csvだけを保存 ★★★
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: results-artifact
          path: output/results.csv
