name: Day-2 LowFloat

on:
  schedule:
    - cron: '5 20 * * 1-5'
    - cron: '5 21 * * 1-5'
  workflow_dispatch:
    inputs:
      step_to_run:
        description: 'テスト実行するステップ (A or B)'
        required: false
        default: ''

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      # ★★★ここからが追加部分★★★
      # 仕事Bの場合だけ、仕事Aが作ったファイルをダウンロードする
      - name: Download previous watchlist if Step B
        # 手動実行でBが選ばれたか、スケジュール実行でBの時間帯だったら、このステップを実行
        if: github.event.inputs.step_to_run == 'B' || (github.event_name == 'schedule' && github.run_attempt == '1' && github.run_number > 1)
        uses: dawidd6/action-download-artifact@v3
        with:
          # 最新の実行から "watchlist-csv" をダウンロード
          name: watchlist-csv
          path: output
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # ★★★ここまで★★★
          
      - name: Install dependencies and Run script
        run: |
          pip install -r requirements.txt
          python main.py
        env:
          DISCORD_HOOK:  ${{ secrets.DISCORD_HOOK }}
          MANUAL_STEP: ${{ github.event.inputs.step_to_run }}
          
      # ★★★ここからが追加部分★★★
      # 仕事Aの場合だけ、作ったファイルをアップロードする
      - name: Upload watchlist if Step A
        if: github.event.inputs.step_to_run == 'A' || (github.event_name == 'schedule' && contains(github.run_id, 'A')) # A rough way to distinguish
        uses: actions/upload-artifact@v4
        with:
          name: watchlist-csv
          path: output/prev100_*.csv
      # ★★★ここまで★★★
