name: Day-2 LowFloat Stock Analyzer

on:
  schedule:
    # 日本時間 AM 05:05 (UTC 20:05) に仕事Aを実行
    - cron: '5 20 * * 1-5'
    # 日本時間 AM 06:05 (UTC 21:05) に仕事Bを実行
    - cron: '5 21 * * 1-5'
  
  workflow_dispatch:
    inputs:
      step_to_run:
        description: 'テスト実行するステップ (A or B)'
        required: false
        default: ''

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # 仕事Bの場合だけ、最新の仕事AのArtifactsをダウンロードする
      - name: Download Watchlist Artifact (for Step B)
        if: ${{ github.event.inputs.step_to_run == 'B' || github.event_name == 'schedule' }}
        uses: actions/download-artifact@v4 # ★ 公式アクションの最新版v4を使う
        with:
          name: analysis-artifacts
          path: output

      - name: Install and Run
        run: |
          pip install -r requirements.txt
          python main.py
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
          MANUAL_STEP: ${{ github.event.inputs.step_to_run }}

      # 仕事Aの場合だけ、ファイルをArtifactsとしてアップロードする
      - name: Upload Watchlist & Results Artifacts
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }} # 常にアップロードする
        uses: actions/upload-artifact@v4
        with:
          name: analysis-artifacts
          path: output/
