name: Stock Analysis Workflow

on:
  workflow_dispatch:

jobs:
  fetch:
    name: Step A - Fetch Watchlist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install and Run
        run: |
          pip install -r requirements.txt
          python step_a_fetch.py
      - uses: actions/upload-artifact@v4
        with:
          name: analysis-artifacts
          path: output/

  notify:
    name: Step B - Notify and Simulate
    runs-on: ubuntu-latest
    needs: fetch
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - uses: actions/download-artifact@v4
        with:
          name: analysis-artifacts
          path: output
      - name: Install and Run
        run: |
          pip install -r requirements.txt
          python step_b_notify.py
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
