# .github/workflows/task-b-workflow.yml

name: Step B - Simulate and Collect Data

on:
  # 【重要】トリガーを schedule から workflow_run に変更
  workflow_run:
    # 'Step A - Fetch and Notify' という名前のワークフローを監視する
    workflows: ["Step A - Fetch and Notify"]
    # ワークフローが「完了」したときにトリガーする
    types:
      - completed
  
  # 手動実行も残しておく
  workflow_dispatch:

jobs:
  simulate:
    name: Simulate and Collect
    # 【重要】トリガー元のワークフローが「成功」した場合のみ、このジョブを実行する
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # workflow_run でトリガーされた場合、トリガー元のアーティファクトを自動で探しに行く
      - name: Download Watchlist from triggering workflow
        uses: actions/download-artifact@v4
        with:
          name: watchlist-artifact
          path: output
          
      - name: Download All Previous Results (if exists)
        uses: actions/download-artifact@v4
        with:
          name: results-artifact
          path: output
        continue-on-error: true

      - name: Install dependencies and Run task_b
        run: |
          pip install -r requirements.txt
          python task_b_simulate.py
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
          
      - name: Upload Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-artifact
          path: output/results.csv
          retention-days: 90
