# .github/workflows/task-b-workflow.yml

name: Step B - Simulate and Collect Data

on:
  workflow_run:
    workflows: ["Step A - Fetch and Notify"]
    types:
      - completed
  workflow_dispatch:

jobs:
  simulate:
    name: Simulate and Collect
    # 成功した時だけ実行する条件は維持
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # ★★★ ここからが重要な修正箇所 ★★★
      # より高機能なサードパーティ製アクションを使用する
      - name: Download Watchlist from Step A workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          # workflow_runイベントをトリガーしたワークフローのIDを指定
          run_id: ${{ github.event.workflow_run.id }}
          # ダウンロードしたいアーティファクトの名前
          name: watchlist-artifact
          # 保存先のパス
          path: output
      # ★★★ 修正ここまで ★★★
          
      # results-artifactのダウンロードは、以前の方法でも問題ないことが多いが、念のためこちらも合わせる
      - name: Download All Previous Results (if exists)
        uses: dawidd6/action-download-artifact@v6
        with:
          # こちらは、このワークフロー（Step B）の最新の成功した実行から探す
          workflow: ${{ github.workflow }}
          # 成功した実行に限定
          workflow_conclusion: success
          name: results-artifact
          path: output
        # このアクションは、アーティファクトが見つからない場合、デフォルトで失敗しないので continue-on-error は不要

      - name: Install dependencies and Run task_b
        run: |
          pip install -r requirements.txt
          python task_b_simulate.py
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
          
      - name: Upload Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-artifact
          path: output/results.csv
          retention-days: 90
